### ISSUE TITLE
make filmDS consistent

### ISSUE THREAD

**Issue by umlaeute** [umlaeute/Gem#180]
this is a meta ticket for the following issues:
- [x] #63 (stops loading after load-failure)
- [x] #68 (EOM reporting)
- [x] #69 (colorspace)
- [x] #160 (don't loop at EOM)
- [x] #161 (erroneous EOM detection)
- [x] #163 (auto)
- [x] #190 (random access)
- [ ] speed! (decoding speed should not be drastically worse than the filmDS code from last release).

**Comment by umlaeute** [comment]
this is also related to #32

**Comment by umlaeute** [comment]
all issues seem to be resolved apart from the "speed" one, which i currently have to nerve to setup a test-bed.
let's hope that the degradation is not too bad (if at all)
